using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace ArduinoMacro
{
    public enum MacroKey : byte
    {
        SPACE = 0x20,
        D0 = 0x30,
        D1 = 0x31,
        D2 = 0x32,
        D3 = 0x33,
        D4 = 0x34,
        D5 = 0x35,
        D6 = 0x36,
        D7 = 0x37,
        D8 = 0x38,
        D9 = 0x39,

        A = 0x41,
        B = 0x42,
        C = 0x43,
        D = 0x44,
        E = 0x45,
        F = 0x46,
        G = 0x47,
        H = 0x48,
        I = 0x49,
        J = 0x4A,
        K = 0x4B,
        L = 0x4C,
        M = 0x4D,
        N = 0x4E,
        O = 0x4F,
        P = 0x50,
        Q = 0x51,
        R = 0x52,
        S = 0x53,
        T = 0x54,
        U = 0x55,
        V = 0x56,
        W = 0x57,
        X = 0x58,
        Y = 0x59,
        Z = 0x5A,

        // Modifiers
        LEFT_CTRL = 0x80,
        LEFT_SHIFT = 0x81,
        LEFT_ALT = 0x82,
        LEFT_GUI = 0x83,
        RIGHT_CTRL = 0x84,
        RIGHT_SHIFT = 0x85,
        RIGHT_ALT = 0x86,
        RIGHT_GUI = 0x87,

        // Misc keys
        UP_ARROW = 0xDA,
        DOWN_ARROW = 0xD9,
        LEFT_ARROW = 0xD8,
        RIGHT_ARROW = 0xD7,
        BACKSPACE = 0xB2,
        TAB = 0xB3,
        RETURN = 0xB0,
        MENU = 0xED,// "Keyboard Application" in USB standard
        ESC = 0xB1,
        INSERT = 0xD1,
        DELETE = 0xD4,
        PAGE_UP = 0xD3,
        PAGE_DOWN = 0xD6,
        HOME = 0xD2,
        END = 0xD5,
        CAPS_LOCK = 0xC1,
        PRINT_SCREEN = 0xCE,// Print Screen / SysRq
        SCROLL_LOCK = 0xCF,
        PAUSE = 0xD0,// Pause / Break

        // Numeric keypad
        NUM_LOCK = 0xDB,
        NUMPAD_SLASH = 0xDC,
        NUMPAD_ASTERISK = 0xDD,
        NUMPAD_MINUS = 0xDE,
        NUMPAD_PLUS = 0xDF,
        NUMPAD_ENTER = 0xE0,
        NUMPAD_1 = 0xE1,
        NUMPAD_2 = 0xE2,
        NUMPAD_3 = 0xE3,
        NUMPAD_4 = 0xE4,
        NUMPAD_5 = 0xE5,
        NUMPAD_6 = 0xE6,
        NUMPAD_7 = 0xE7,
        NUMPAD_8 = 0xE8,
        NUMPAD_9 = 0xE9,
        NUMPAD_0 = 0xEA,
        NUMPAD_DOT = 0xEB,

        // Function keys
        F1 = 0xC2,
        F2 = 0xC3,
        F3 = 0xC4,
        F4 = 0xC5,
        F5 = 0xC6,
        F6 = 0xC7,
        F7 = 0xC8,
        F8 = 0xC9,
        F9 = 0xCA,
        F10 = 0xCB,
        F11 = 0xCC,
        F12 = 0xCD,
        F13 = 0xF0,
        F14 = 0xF1,
        F15 = 0xF2,
        F16 = 0xF3,
        F17 = 0xF4,
        F18 = 0xF5,
        F19 = 0xF6,
        F20 = 0xF7,
        F21 = 0xF8,
        F22 = 0xF9,
        F23 = 0xFA,
        F24 = 0xFB,
    }

    public class MacroKeys
    {
        public static MacroKey[] Keys =
        {
            MacroKey.SPACE,
            MacroKey.D0,
            MacroKey.D1,
            MacroKey.D2,
            MacroKey.D3,
            MacroKey.D4,
            MacroKey.D5,
            MacroKey.D6,
            MacroKey.D7,
            MacroKey.D8,
            MacroKey.D9,
            MacroKey.A,
            MacroKey.B,
            MacroKey.C,
            MacroKey.D,
            MacroKey.E,
            MacroKey.F,
            MacroKey.G,
            MacroKey.H,
            MacroKey.I,
            MacroKey.J,
            MacroKey.K,
            MacroKey.L,
            MacroKey.M,
            MacroKey.N,
            MacroKey.O,
            MacroKey.P,
            MacroKey.Q,
            MacroKey.R,
            MacroKey.S,
            MacroKey.T,
            MacroKey.U,
            MacroKey.V,
            MacroKey.W,
            MacroKey.X,
            MacroKey.Y,
            MacroKey.Z,
            MacroKey.LEFT_CTRL,
            MacroKey.LEFT_SHIFT,
            MacroKey.LEFT_ALT,
            MacroKey.LEFT_GUI,
            MacroKey.RIGHT_CTRL,
            MacroKey.RIGHT_SHIFT,
            MacroKey.RIGHT_ALT,
            MacroKey.RIGHT_GUI,
            MacroKey.UP_ARROW,
            MacroKey.DOWN_ARROW,
            MacroKey.LEFT_ARROW,
            MacroKey.RIGHT_ARROW,
            MacroKey.BACKSPACE,
            MacroKey.TAB,
            MacroKey.RETURN,
            MacroKey.MENU,
            MacroKey.ESC,
            MacroKey.INSERT,
            MacroKey.DELETE,
            MacroKey.PAGE_UP,
            MacroKey.PAGE_DOWN,
            MacroKey.HOME,
            MacroKey.END,
            MacroKey.CAPS_LOCK,
            MacroKey.PRINT_SCREEN,
            MacroKey.SCROLL_LOCK,
            MacroKey.PAUSE,
            MacroKey.NUM_LOCK,
            MacroKey.NUMPAD_SLASH,
            MacroKey.NUMPAD_ASTERISK,
            MacroKey.NUMPAD_MINUS,
            MacroKey.NUMPAD_PLUS,
            MacroKey.NUMPAD_ENTER,
            MacroKey.NUMPAD_1,
            MacroKey.NUMPAD_2,
            MacroKey.NUMPAD_3,
            MacroKey.NUMPAD_4,
            MacroKey.NUMPAD_5,
            MacroKey.NUMPAD_6,
            MacroKey.NUMPAD_7,
            MacroKey.NUMPAD_8,
            MacroKey.NUMPAD_9,
            MacroKey.NUMPAD_0,
            MacroKey.NUMPAD_DOT,
            MacroKey.F1,
            MacroKey.F2,
            MacroKey.F3,
            MacroKey.F4,
            MacroKey.F5,
            MacroKey.F6,
            MacroKey.F7,
            MacroKey.F8,
            MacroKey.F9,
            MacroKey.F10,
            MacroKey.F11,
            MacroKey.F12,
            MacroKey.F13,
            MacroKey.F14,
            MacroKey.F15,
            MacroKey.F16,
            MacroKey.F17,
            MacroKey.F18,
            MacroKey.F19,
            MacroKey.F20,
            MacroKey.F21,
            MacroKey.F22,
            MacroKey.F23,
            MacroKey.F24,

        };
    }
}
